#include <iostream>
#include <string>

using namespace std;

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

int main() {
    std::uint64_t sum = 0;
    uint64_t fib = 0;
    int fn1 = 1;
    int fn2 = 1;
    while (fib < 4000000){
        // get fib sequence fn = fn-1 + fn-2
        fib = fn1 + fn2;
        fn2 = fn1;
        fn1 = fib;
        //cout << "fib: " << fib << endl;
        // mod test
        if (fib % 2 == 0){
            sum = sum + fib;
            //cout << sum << endl;
        }

    }
    cout << "fib: " << fib << endl;
    cout << "Answer: " << sum << endl;

    return 0;
}